#!/usr/bin/env python3
"""Generate Trinote/Resources/Localizable.xcstrings from embedded translations."""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

LOCALES = ("es", "it", "fr", "de", "ru", "ar", "hi", "hu", "cs", "pl")

# Apostrophe in “note’s” is U+2019 (RIGHT SINGLE QUOTATION MARK), matching Swift source.
NOTE_APOS = "\u2019"
NOTE_S = f"note{NOTE_APOS}s"

BR_IN_CACHE = f"Could not resolve the {NOTE_S} branch in the local cache."
BR_IN_TREE = f"Could not resolve the {NOTE_S} branch in the tree."


def T(
    es: str,
    it: str,
    fr: str,
    de: str,
    ru: str,
    ar: str,
    hi: str,
    hu: str,
    cs: str,
    pl: str,
) -> dict[str, str]:
    return {
        "es": es,
        "it": it,
        "fr": fr,
        "de": de,
        "ru": ru,
        "ar": ar,
        "hi": hi,
        "hu": hu,
        "cs": cs,
        "pl": pl,
    }


STRINGS: dict[str, dict[str, str]] = {
    " (ios-sync-conflict)": T(
        " (conflicto-ios-sync)",
        " (ios-sync-conflict)",
        " (conflit-ios-sync)",
        " (ios-sync-conflict)",
        " (ios-sync-conflict)",
        " (تعارض-مزامنة-ios)",
        " (ios-सिंक-संघर्ष)",
        " (ios-sync-ütközés)",
        " (ios-sync-conflict)",
        " (konflikt-ios-sync)",
    ),
    "(empty line)": T(
        "(línea vacía)",
        "(riga vuota)",
        "(ligne vide)",
        "(leere Zeile)",
        "(пустая строка)",
        "(سطر فارغ)",
        "(खाली पंक्ति)",
        "(üres sor)",
        "(prázdný řádek)",
        "(pusta linia)",
    ),
    "A note cannot be moved under itself.": T(
        "Una nota no puede moverse debajo de sí misma.",
        "Una nota non può essere spostata sotto se stessa.",
        "Une note ne peut pas être déplacée sous elle-même.",
        "Eine Notiz kann nicht unter sich selbst verschoben werden.",
        "Заметку нельзя переместить под саму себя.",
        "لا يمكن نقل الملاحظة لتصبح تحت نفسها.",
        "किसी नोट को स्वयं के अंतर्गत नहीं ले जा सकते।",
        "Egy jegyzet nem helyezhető önmaga alá.",
        "Poznámku nelze přesunout pod sebe samu.",
        "Notatki nie można przenieść pod samą siebie.",
    ),
    "Add to Favorites": T(
        "Añadir a favoritos",
        "Aggiungi ai preferiti",
        "Ajouter aux favoris",
        "Zu Favoriten hinzufügen",
        "Добавить в избранное",
        "إضافة إلى المفضلة",
        "पसंदीदा में जोड़ें",
        "Hozzáadás a kedvencekhez",
        "Přidat do oblíbených",
        "Dodaj do ulubionych",
    ),
    "Add to favorites": T(
        "Añadir a favoritos",
        "Aggiungi ai preferiti",
        "Ajouter aux favoris",
        "Zu Favoriten hinzufügen",
        "В избранное",
        "إضافة إلى المفضلة",
        "पसंदीदा में जोड़ें",
        "Kedvencekhez adás",
        "Přidat mezi oblíbené",
        "Dodaj do ulubionych",
    ),
    "Bulk actions": T(
        "Acciones en bloque",
        "Azioni di gruppo",
        "Actions groupées",
        "Massenaktionen",
        "Массовые действия",
        "إجراءات جماعية",
        "बल्क कार्रवाई",
        "Tömeges műveletek",
        "Hromadné akce",
        "Akcje zbiorcze",
    ),
    "Cancel": T(
        "Cancelar",
        "Annulla",
        "Annuler",
        "Abbrechen",
        "Отмена",
        "إلغاء",
        "रद्द करें",
        "Mégse",
        "Zrušit",
        "Anuluj",
    ),
    "Cancel Editing": T(
        "Cancelar edición",
        "Annulla modifica",
        "Annuler la modification",
        "Bearbeitung abbrechen",
        "Отменить редактирование",
        "إلغاء التحرير",
        "संपादन रद्द करें",
        "Szerkesztés megszakítása",
        "Zrušit úpravy",
        "Anuluj edycję",
    ),
    "Cancel editing": T(
        "Cancelar edición",
        "Annulla modifica",
        "Annuler la modification",
        "Bearbeitung abbrechen",
        "Отменить правку",
        "إلغاء التحرير",
        "संपादन रद्द करें",
        "Szerkesztés megszakítása",
        "Zrušit úpravy",
        "Anuluj edycję",
    ),
    "Cannot change sharing while offline.": T(
        "No se puede cambiar el uso compartido sin conexión.",
        "Impossibile modificare la condivisione senza connessione.",
        "Impossible de modifier le partage hors ligne.",
        "Freigabe kann offline nicht geändert werden.",
        "Нельзя изменить общий доступ в автономном режиме.",
        "لا يمكن تغيير المشاركة دون اتصال.",
        "ऑफ़लाइन रहते हुए साझाकरण नहीं बदला जा सकता।",
        "Megosztás offline nem módosítható.",
        "Sdílení nelze offline změnit.",
        "Nie można zmienić udostępniania w trybie offline.",
    ),
    "Cannot move while offline.": T(
        "No se puede mover sin conexión.",
        "Impossibile spostare senza connessione.",
        "Impossible de déplacer hors ligne.",
        "Verschieben offline nicht möglich.",
        "Нельзя переместить в автономном режиме.",
        "لا يمكن النقل دون اتصال.",
        "ऑफ़लाइन रहते हुए स्थानांतरण नहीं हो सकता।",
        "Offline nem lehet áthelyezni.",
        "Offline nelze přesunout.",
        "Nie można przenieść w trybie offline.",
    ),
    "Choose Parent": T(
        "Elegir carpeta",
        "Scegli genitore",
        "Choisir le parent",
        "Übergeordnete Notiz wählen",
        "Выберите родителя",
        "اختر المجلد الأب",
        "मूल चुनें",
        "Szülő kiválasztása",
        "Zvolit nadřazenou položku",
        "Wybierz element nadrzędny",
    ),
    "Choose where to move the note. Open folders, then tap a note to select it as the new parent.": T(
        "Elige dónde mover la nota. Abre carpetas y toca una nota para seleccionarla como nueva carpeta.",
        "Scegli dove spostare la nota. Apri le cartelle, poi tocca una nota per selezionarla come nuovo genitore.",
        "Choisissez où déplacer la note. Ouvrez des dossiers, puis touchez une note pour l’utiliser comme parent.",
        "Wählen Sie, wohin die Notiz verschoben wird. Öffnen Sie Ordner und tippen Sie auf eine Notiz als neues übergeordnetes Element.",
        "Выберите, куда переместить заметку. Откройте папки и нажмите заметку, чтобы сделать её новым родителем.",
        "اختر مكان نقل الملاحظة. افتح المجلدات، ثم انقر ملاحظة لاختيارها كأب جديد.",
        "नोट कहाँ ले जाना है चुनें। फ़ोल्डर खोलें, फिर नए मूल के रूप में चुनने के लिए किसी नोट पर टैप करें।",
        "Válaszd ki, hova kerüljön a jegyzet. Nyisd meg a mappákat, majd koppints egy jegyzetre új szülőként.",
        "Vyberte, kam poznámku přesunout. Otevřete složky a klepněte na poznámku jako nového rodiče.",
        "Wybierz, dokąd przenieść notatkę. Otwórz foldery, a następnie stuknij notatkę, aby wybrać ją jako nowy element nadrzędny.",
    ),
    "Choose where to place the duplicates. Use the tree to open folders, then tap a note to select it as the parent.": T(
        "Elige dónde colocar los duplicados. Usa el árbol para abrir carpetas y toca una nota como carpeta.",
        "Scegli dove mettere i duplicati. Usa l’albero per aprire le cartelle, poi tocca una nota come genitore.",
        "Choisissez où placer les doublons. Utilisez l’arborescence pour ouvrir des dossiers, puis touchez une note comme parent.",
        "Wählen Sie den Ort für die Duplikate. Öffnen Sie im Baum Ordner und tippen Sie auf eine Notiz als übergeordnetes Element.",
        "Выберите, куда поместить копии. Откройте папки в дереве и нажмите заметку как родителя.",
        "اختر مكان النسخ المكررة. استخدم الشجرة لفتح المجلدات، ثم انقر ملاحظة كأب.",
        "डुप्लिकेट कहाँ रखें चुनें। फ़ोल्डर खोलने के लिए ट्री का उपयोग करें, फिर मूल के रूप में किसी नोट पर टैप करें।",
        "Válaszd ki, hova kerüljenek a másolatok. A fában nyisd meg a mappákat, majd koppints egy jegyzetre szülőként.",
        "Vyberte, kam umístit duplicity. Ve stromu otevřete složky a klepněte na poznámku jako rodiče.",
        "Wybierz, gdzie umieścić duplikaty. Użyj drzewa, aby otworzyć foldery, a następnie stuknij notatkę jako element nadrzędny.",
    ),
    "Cloned note": T(
        "Nota clonada",
        "Nota clonata",
        "Note clonée",
        "Kopierte Notiz",
        "Клон заметки",
        "ملاحظة مستنسخة",
        "क्लोन किया गया नोट",
        "Klónozott jegyzet",
        "Klonovaná poznámka",
        "Sklonowana notatka",
    ),
    "Close": T(
        "Cerrar",
        "Chiudi",
        "Fermer",
        "Schließen",
        "Закрыть",
        "إغلاق",
        "बंद करें",
        "Bezárás",
        "Zavřít",
        "Zamknij",
    ),
    "Close find bar": T(
        "Cerrar barra de búsqueda",
        "Chiudi barra di ricerca",
        "Fermer la barre de recherche",
        "Suchleiste schließen",
        "Закрыть панель поиска",
        "إغلاق شريط البحث",
        "खोज पट्टी बंद करें",
        "Keresősáv bezárása",
        "Zavřít vyhledávací panel",
        "Zamknij pasek wyszukiwania",
    ),
    "Copy share link": T(
        "Copiar enlace compartido",
        "Copia link di condivisione",
        "Copier le lien de partage",
        "Freigabelink kopieren",
        "Копировать ссылку общего доступа",
        "نسخ رابط المشاركة",
        "साझा लिंक कॉपी करें",
        "Megosztási hivatkozás másolása",
        "Kopírovat odkaz ke sdílení",
        "Kopiuj link udostępniania",
    ),
    "Could not load this note.": T(
        "No se pudo cargar esta nota.",
        "Impossibile caricare questa nota.",
        "Impossible de charger cette note.",
        "Diese Notiz konnte nicht geladen werden.",
        "Не удалось загрузить эту заметку.",
        "تعذّر تحميل هذه الملاحظة.",
        "यह नोट लोड नहीं हो सका।",
        "A jegyzet nem tölthető be.",
        "Tuto poznámku se nepodařilo načíst.",
        "Nie udało się wczytać tej notatki.",
    ),
    BR_IN_CACHE: T(
        "No se pudo resolver la rama de la nota en la caché local.",
        "Impossibile risolvere il ramo della nota nella cache locale.",
        "Impossible de résoudre la branche de la note dans le cache local.",
        "Der Zweig der Notiz konnte im lokalen Cache nicht ermittelt werden.",
        "Не удалось определить ветку заметки в локальном кэше.",
        "تعذّر تحديد فرع الملاحظة في الذاكرة المؤقتة المحلية.",
        "स्थानीय कैश में नोट की शाखा हल नहीं की जा सकी।",
        "A jegyzet ága nem oldható fel a helyi gyorsítótárban.",
        "Větev poznámky se nepodařilo vyřešit v místní mezipaměti.",
        "Nie można rozwiązać gałęzi notatki w lokalnej pamięci podręcznej.",
    ),
    BR_IN_TREE: T(
        "No se pudo resolver la rama de la nota en el árbol.",
        "Impossibile risolvere il ramo della nota nell’albero.",
        "Impossible de résoudre la branche de la note dans l’arborescence.",
        "Der Zweig der Notiz konnte im Baum nicht ermittelt werden.",
        "Не удалось определить ветку заметки в дереве.",
        "تعذّر تحديد فرع الملاحظة في الشجرة.",
        "ट्री में नोट की शाखा हल नहीं की जा सकी।",
        "A jegyzet ága nem oldható fel a fában.",
        "Větev poznámky se nepodařilo vyřešit ve stromu.",
        "Nie można rozwiązać gałęzi notatki w drzewie.",
    ),
    "Couldn't load": T(
        "No se pudo cargar",
        "Impossibile caricare",
        "Échec du chargement",
        "Laden fehlgeschlagen",
        "Не удалось загрузить",
        "تعذّر التحميل",
        "लोड नहीं हो सका",
        "Nem sikerült betölteni",
        "Nepodařilo se načíst",
        "Nie udało się wczytać",
    ),
    "Couldn't load note content for previews.": T(
        "No se pudo cargar el contenido de la nota para las vistas previas.",
        "Impossibile caricare il contenuto della nota per le anteprime.",
        "Impossible de charger le contenu de la note pour les aperçus.",
        "Notizinhalt für Vorschauen konnte nicht geladen werden.",
        "Не удалось загрузить содержимое заметки для предпросмотра.",
        "تعذّر تحميل محتوى الملاحظة للمعاينات.",
        "पूर्वावलोकन के लिए नोट सामग्री लोड नहीं हो सकी।",
        "A jegyzet tartalma nem tölthető be az előnézetekhez.",
        "Obsah poznámky pro náhledy se nepodařilo načíst.",
        "Nie udało się wczytać treści notatki do podglądów.",
    ),
    "Couldn't update sharing": T(
        "No se pudo actualizar el uso compartido",
        "Impossibile aggiornare la condivisione",
        "Impossible de mettre à jour le partage",
        "Freigabe konnte nicht aktualisiert werden",
        "Не удалось обновить общий доступ",
        "تعذّر تحديث المشاركة",
        "साझाकरण अपडेट नहीं हो सका",
        "A megosztás frissítése sikertelen",
        "Sdílení se nepodařilo aktualizovat",
        "Nie udało się zaktualizować udostępniania",
    ),
    "Delete Note": T(
        "Eliminar nota",
        "Elimina nota",
        "Supprimer la note",
        "Notiz löschen",
        "Удалить заметку",
        "حذف الملاحظة",
        "नोट हटाएँ",
        "Jegyzet törlése",
        "Smazat poznámku",
        "Usuń notatkę",
    ),
    "Done": T(
        "Hecho",
        "Fatto",
        "Terminé",
        "Fertig",
        "Готово",
        "تم",
        "हो गया",
        "Kész",
        "Hotovo",
        "Gotowe",
    ),
    "Duplicate Note": T(
        "Duplicar nota",
        "Duplica nota",
        "Dupliquer la note",
        "Notiz duplizieren",
        "Дублировать заметку",
        "تكرار الملاحظة",
        "नोट डुप्लिकेट करें",
        "Jegyzet duplikálása",
        "Duplikovat poznámku",
        "Duplikuj notatkę",
    ),
    "Duplicate note": T(
        "Duplicar nota",
        "Duplica nota",
        "Dupliquer la note",
        "Notiz duplizieren",
        "Дублировать заметку",
        "تكرار الملاحظة",
        "नोट डुप्लिकेट करें",
        "Jegyzet duplikálása",
        "Duplikovat poznámku",
        "Duplikuj notatkę",
    ),
    "Edit": T(
        "Editar",
        "Modifica",
        "Modifier",
        "Bearbeiten",
        "Изменить",
        "تحرير",
        "संपादित करें",
        "Szerkesztés",
        "Upravit",
        "Edytuj",
    ),
    "Edit Note": T(
        "Editar nota",
        "Modifica nota",
        "Modifier la note",
        "Notiz bearbeiten",
        "Редактировать заметку",
        "تحرير الملاحظة",
        "नोट संपादित करें",
        "Jegyzet szerkesztése",
        "Upravit poznámku",
        "Edytuj notatkę",
    ),
    "Edit note": T(
        "Editar nota",
        "Modifica nota",
        "Modifier la note",
        "Notiz bearbeiten",
        "Редактировать заметку",
        "تحرير الملاحظة",
        "नोट संपादित करें",
        "Jegyzet szerkesztése",
        "Upravit poznámku",
        "Edytuj notatkę",
    ),
    "Find on Page": T(
        "Buscar en la página",
        "Trova nella pagina",
        "Rechercher dans la page",
        "Auf Seite suchen",
        "Искать на странице",
        "البحث في الصفحة",
        "पृष्ठ पर खोजें",
        "Keresés az oldalon",
        "Najít na stránce",
        "Szukaj na stronie",
    ),
    "Find on page": T(
        "Buscar en la página",
        "Trova nella pagina",
        "Rechercher dans la page",
        "Auf Seite suchen",
        "Искать на странице",
        "البحث في الصفحة",
        "पृष्ठ पर खोजें",
        "Keresés az oldalon",
        "Najít na stránce",
        "Szukaj na stronie",
    ),
    "Hide Find Bar": T(
        "Ocultar barra de búsqueda",
        "Nascondi barra di ricerca",
        "Masquer la barre de recherche",
        "Suchleiste ausblenden",
        "Скрыть панель поиска",
        "إخفاء شريط البحث",
        "खोज पट्टी छिपाएँ",
        "Keresősáv elrejtése",
        "Skrýt vyhledávací panel",
        "Ukryj pasek wyszukiwania",
    ),
    "Hide find bar": T(
        "Ocultar barra de búsqueda",
        "Nascondi barra di ricerca",
        "Masquer la barre de recherche",
        "Suchleiste ausblenden",
        "Скрыть панель поиска",
        "إخفاء شريط البحث",
        "खोज पट्टी छिपाएँ",
        "Keresősáv elrejtése",
        "Skrýt vyhledávací panel",
        "Ukryj pasek wyszukiwania",
    ),
    "Hide note details": T(
        "Ocultar detalles de la nota",
        "Nascondi dettagli nota",
        "Masquer les détails de la note",
        "Notizdetails ausblenden",
        "Скрыть сведения о заметке",
        "إخفاء تفاصيل الملاحظة",
        "नोट विवरण छिपाएँ",
        "Jegyzet részleteinek elrejtése",
        "Skrýt podrobnosti poznámky",
        "Ukryj szczegóły notatki",
    ),
    "Loading shared notes…": T(
        "Cargando notas compartidas…",
        "Caricamento note condivise…",
        "Chargement des notes partagées…",
        "Geteilte Notizen werden geladen …",
        "Загрузка общих заметок…",
        "جارٍ تحميل الملاحظات المشتركة…",
        "साझा नोट लोड हो रहे हैं…",
        "Megosztott jegyzetek betöltése…",
        "Načítání sdílených poznámek…",
        "Wczytywanie udostępnionych notatek…",
    ),
    "More": T(
        "Más",
        "Altro",
        "Plus",
        "Mehr",
        "Ещё",
        "المزيد",
        "और",
        "Továbbiak",
        "Další",
        "Więcej",
    ),
    "Move": T(
        "Mover",
        "Sposta",
        "Déplacer",
        "Verschieben",
        "Переместить",
        "نقل",
        "ले जाएँ",
        "Áthelyezés",
        "Přesunout",
        "Przenieś",
    ),
    "Move Note": T(
        "Mover nota",
        "Sposta nota",
        "Déplacer la note",
        "Notiz verschieben",
        "Переместить заметку",
        "نقل الملاحظة",
        "नोट ले जाएँ",
        "Jegyzet áthelyezése",
        "Přesunout poznámku",
        "Przenieś notatkę",
    ),
    "Move to…": T(
        "Mover a…",
        "Sposta in…",
        "Déplacer vers…",
        "Verschieben nach …",
        "Переместить в…",
        "نقل إلى…",
        "ले जाएँ…",
        "Áthelyezés ide…",
        "Přesunout do…",
        "Przenieś do…",
    ),
    "New Note": T(
        "Nota nueva",
        "Nuova nota",
        "Nouvelle note",
        "Neue Notiz",
        "Новая заметка",
        "ملاحظة جديدة",
        "नया नोट",
        "Új jegyzet",
        "Nová poznámka",
        "Nowa notatka",
    ),
    "New child note": T(
        "Nueva nota hija",
        "Nuova nota figlia",
        "Nouvelle sous-note",
        "Neue untergeordnete Notiz",
        "Новая дочерняя заметка",
        "ملاحظة فرعية جديدة",
        "नया उप-नोट",
        "Új alárendelt jegyzet",
        "Nová podřízená poznámka",
        "Nowa notatka podrzędna",
    ),
    "New top-level note": T(
        "Nueva nota de nivel superior",
        "Nuova nota di primo livello",
        "Nouvelle note de niveau supérieur",
        "Neue Notiz auf oberster Ebene",
        "Новая заметка верхнего уровня",
        "ملاحظة جديدة في المستوى الأعلى",
        "नया शीर्ष-स्तरीय नोट",
        "Új legfelső szintű jegyzet",
        "Nová poznámka na nejvyšší úrovni",
        "Nowa notatka najwyższego poziomu",
    ),
    "Next match": T(
        "Siguiente coincidencia",
        "Corrispondenza successiva",
        "Occurrence suivante",
        "Nächster Treffer",
        "Следующее совпадение",
        "التطابق التالي",
        "अगला मिलान",
        "Következő találat",
        "Další shoda",
        "Następne dopasowanie",
    ),
    "No matching lines in the loaded text (previews use plain text; very long notes may differ slightly from in-page find).": T(
        "No hay líneas coincidentes en el texto cargado (las vistas previas usan texto sin formato; las notas muy largas pueden diferir ligeramente de la búsqueda en la página).",
        "Nessuna riga corrispondente nel testo caricato (le anteprime usano testo normale; note molto lunghe possono differire leggermente dalla ricerca nella pagina).",
        "Aucune ligne correspondante dans le texte chargé (les aperçus utilisent du texte brut ; les très longues notes peuvent différer légèrement de la recherche dans la page).",
        "Keine passenden Zeilen im geladenen Text (Vorschauen nutzen Nur-Text; bei sehr langen Notizen kann es leichte Abweichungen zur Suche auf der Seite geben).",
        "Нет совпадений в загруженном тексте (предпросмотры используют обычный текст; для очень длинных заметок возможны небольшие отличия от поиска на странице).",
        "لا توجد أسطر مطابقة في النص المحمّل (تستخدم المعاينات نصًا عاديًا؛ قد تختلف الملاحظات الطويلة جدًا قليلاً عن البحث داخل الصفحة).",
        "लोड किए गए पाठ में कोई मिलान पंक्ति नहीं (पूर्वावलोकन सादा पाठ उपयोग करते हैं; बहुत लंबे नोट पृष्ठ-में खोज से थोड़ा भिन्न हो सकते हैं)।",
        "Nincs egyező sor a betöltött szövegben (az előnézetek sima szöveget használnak; nagyon hosszú jegyzeteknél apró eltérések lehetnek az oldalon belüli kereséshez képest).",
        "V načteném textu nejsou žádné odpovídající řádky (náhledy používají prostý text; u velmi dlouhých poznámek se může výsledek mírně lišit od vyhledávání na stránce).",
        "Brak pasujących linii w wczytanym tekście (podglądy używają zwykłego tekstu; przy bardzo długich notatkach mogą być drobne różnice względem wyszukiwania na stronie).",
    ),
    "No shared notes": T(
        "Sin notas compartidas",
        "Nessuna nota condivisa",
        "Aucune note partagée",
        "Keine geteilten Notizen",
        "Нет общих заметок",
        "لا توجد ملاحظات مشتركة",
        "कोई साझा नोट नहीं",
        "Nincs megosztott jegyzet",
        "Žádné sdílené poznámky",
        "Brak udostępnionych notatek",
    ),
    "Not connected to a server.": T(
        "No hay conexión a un servidor.",
        "Nessuna connessione al server.",
        "Pas connecté à un serveur.",
        "Keine Verbindung zu einem Server.",
        "Нет подключения к серверу.",
        "غير متصل بخادم.",
        "किसी सर्वर से कनेक्ट नहीं है।",
        "Nincs kapcsolat a kiszolgálóval.",
        "Není připojení k serveru.",
        "Brak połączenia z serwerem.",
    ),
    "Note (ios-sync-conflict)": T(
        "Nota (conflicto-ios-sync)",
        "Nota (ios-sync-conflict)",
        "Note (conflit-ios-sync)",
        "Notiz (ios-sync-conflict)",
        "Заметка (ios-sync-conflict)",
        "ملاحظة (تعارض-مزامنة-ios)",
        "नोट (ios-सिंक-संघर्ष)",
        "Jegyzet (ios-sync-ütközés)",
        "Poznámka (ios-sync-conflict)",
        "Notatka (konflikt-ios-sync)",
    ),
    "Notes": T(
        "Notas",
        "Note",
        "Notes",
        "Notizen",
        "Заметки",
        "ملاحظات",
        "नोट्स",
        "Jegyzetek",
        "Poznámky",
        "Notatki",
    ),
    "Offline — showing cached notes. Connect to refresh.": T(
        "Sin conexión: se muestran notas en caché. Conéctate para actualizar.",
        "Offline: vengono mostrate le note in cache. Connettiti per aggiornare.",
        "Hors ligne — affichage des notes en cache. Connectez-vous pour actualiser.",
        "Offline — zwischengespeicherte Notizen werden angezeigt. Verbinden Sie sich, um zu aktualisieren.",
        "Офлайн — показаны кэшированные заметки. Подключитесь для обновления.",
        "دون اتصال — عرض الملاحظات المخبأة. اتصل للتحديث.",
        "ऑफ़लाइन — कैश किए गए नोट दिख रहे हैं। ताज़ा करने के लिए कनेक्ट करें।",
        "Offline — a gyorsítótárazott jegyzetek láthatók. Csatlakozzon a frissítéshez.",
        "Offline — zobrazují se uložené poznámky. Připojte se pro obnovení.",
        "Offline — wyświetlane są notatki z pamięci podręcznej. Połącz się, aby odświeżyć.",
    ),
    "Previous match": T(
        "Coincidencia anterior",
        "Corrispondenza precedente",
        "Occurrence précédente",
        "Vorheriger Treffer",
        "Предыдущее совпадение",
        "التطابق السابق",
        "पिछला मिलान",
        "Előző találat",
        "Předchozí shoda",
        "Poprzednie dopasowanie",
    ),
    "Protected note": T(
        "Nota protegida",
        "Nota protetta",
        "Note protégée",
        "Geschützte Notiz",
        "Защищённая заметка",
        "ملاحظة محمية",
        "संरक्षित नोट",
        "Védett jegyzet",
        "Chráněná poznámka",
        "Chroniona notatka",
    ),
    "Protected notes cannot be shared.": T(
        "Las notas protegidas no se pueden compartir.",
        "Le note protette non possono essere condivise.",
        "Les notes protégées ne peuvent pas être partagées.",
        "Geschützte Notizen können nicht freigegeben werden.",
        "Защищённые заметки нельзя сделать общими.",
        "لا يمكن مشاركة الملاحظات المحمية.",
        "संरक्षित नोट साझा नहीं किए जा सकते।",
        "A védett jegyzetek nem oszthatók meg.",
        "Chráněné poznámky nelze sdílet.",
        "Chronionych notatek nie można udostępniać.",
    ),
    "Refresh tree": T(
        "Actualizar árbol",
        "Aggiorna albero",
        "Actualiser l’arborescence",
        "Baum aktualisieren",
        "Обновить дерево",
        "تحديث الشجرة",
        "ट्री रीफ़्रेश करें",
        "Fa frissítése",
        "Obnovit strom",
        "Odśwież drzewo",
    ),
    "Remove from Favorites": T(
        "Quitar de favoritos",
        "Rimuovi dai preferiti",
        "Retirer des favoris",
        "Aus Favoriten entfernen",
        "Удалить из избранного",
        "إزالة من المفضلة",
        "पसंदीदा से हटाएँ",
        "Eltávolítás a kedvencekből",
        "Odebrat z oblíbených",
        "Usuń z ulubionych",
    ),
    "Remove from favorites": T(
        "Quitar de favoritos",
        "Rimuovi dai preferiti",
        "Retirer des favoris",
        "Aus Favoriten entfernen",
        "Убрать из избранного",
        "إزالة من المفضلة",
        "पसंदीदा से हटाएँ",
        "Eltávolítás a kedvencekből",
        "Odebrat z oblíbených",
        "Usuń z ulubionych",
    ),
    "Rename note": T(
        "Renombrar nota",
        "Rinomina nota",
        "Renommer la note",
        "Notiz umbenennen",
        "Переименовать заметку",
        "إعادة تسمية الملاحظة",
        "नोट का नाम बदलें",
        "Jegyzet átnevezése",
        "Přejmenovat poznámku",
        "Zmień nazwę notatki",
    ),
    "Retry": T(
        "Reintentar",
        "Riprova",
        "Réessayer",
        "Erneut versuchen",
        "Повторить",
        "إعادة المحاولة",
        "पुनः प्रयास करें",
        "Újra",
        "Zkusit znovu",
        "Spróbuj ponownie",
    ),
    "Save": T(
        "Guardar",
        "Salva",
        "Enregistrer",
        "Speichern",
        "Сохранить",
        "حفظ",
        "सहेजें",
        "Mentés",
        "Uložit",
        "Zapisz",
    ),
    "Saved on this device. Your edit will upload when you're back online.": T(
        "Guardado en este dispositivo. La edición se subirá cuando vuelvas a estar en línea.",
        "Salvato su questo dispositivo. La modifica verrà caricata quando tornerai online.",
        "Enregistré sur cet appareil. Votre modification sera envoyée lorsque vous serez de nouveau en ligne.",
        "Auf diesem Gerät gespeichert. Ihre Bearbeitung wird hochgeladen, sobald Sie wieder online sind.",
        "Сохранено на этом устройстве. Изменение загрузится, когда вы снова будете в сети.",
        "تم الحفظ على هذا الجهاز. سيتم رفع التعديل عند عودة الاتصال.",
        "इस डिवाइस पर सहेजा गया। ऑनलाइन होने पर आपका संपादन अपलोड होगा।",
        "Mentve ezen az eszközön. A szerkesztés feltöltődik, ha újra online leszel.",
        "Uloženo v tomto zařízení. Úpravy se nahrají, až budete znovu online.",
        "Zapisano na tym urządzeniu. Edycja zostanie wysłana po ponownym połączeniu z siecią.",
    ),
    "Share": T(
        "Compartir",
        "Condividi",
        "Partager",
        "Teilen",
        "Поделиться",
        "مشاركة",
        "साझा करें",
        "Megosztás",
        "Sdílet",
        "Udostępnij",
    ),
    "Share a note from its details panel to see it here.": T(
        "Comparte una nota desde su panel de detalles para verla aquí.",
        "Condividi una nota dal pannello dettagli per vederla qui.",
        "Partagez une note depuis son panneau de détails pour la voir ici.",
        "Teilen Sie eine Notiz über das Detailfenster, um sie hier zu sehen.",
        "Поделитесь заметкой из панели сведений, чтобы она появилась здесь.",
        "شارِك ملاحظة من لوحة التفاصيل لعرضها هنا.",
        "इसे यहाँ देखने के लिए विवरण पैनल से किसी नोट को साझा करें।",
        "Osszon meg egy jegyzetet a részletek panelről, hogy itt megjelenjen.",
        "Sdílejte poznámku z panelu podrobností, aby se zobrazila zde.",
        "Udostępnij notatkę z panelu szczegółów, aby pojawiła się tutaj.",
    ),
    "Share link…": T(
        "Enlace compartido…",
        "Link di condivisione…",
        "Lien de partage…",
        "Freigabelink …",
        "Ссылка для общего доступа…",
        "رابط المشاركة…",
        "लिंक साझा करें…",
        "Megosztási hivatkozás…",
        "Odkaz ke sdílení…",
        "Link udostępniania…",
    ),
    "Shared note": T(
        "Nota compartida",
        "Nota condivisa",
        "Note partagée",
        "Geteilte Notiz",
        "Общая заметка",
        "ملاحظة مشتركة",
        "साझा नोट",
        "Megosztott jegyzet",
        "Sdílená poznámka",
        "Udostępniona notatka",
    ),
    "Shared notes": T(
        "Notas compartidas",
        "Note condivise",
        "Notes partagées",
        "Geteilte Notizen",
        "Общие заметки",
        "ملاحظات مشتركة",
        "साझा नोट",
        "Megosztott jegyzetek",
        "Sdílené poznámky",
        "Udostępnione notatki",
    ),
    "Shared notes…": T(
        "Notas compartidas…",
        "Note condivise…",
        "Notes partagées…",
        "Geteilte Notizen …",
        "Общие заметки…",
        "ملاحظات مشتركة…",
        "साझा नोट…",
        "Megosztott jegyzetek…",
        "Sdílené poznámky…",
        "Udostępnione notatki…",
    ),
    "Sharing requires connection": T(
        "Compartir requiere conexión",
        "La condivisione richiede la connessione",
        "Le partage nécessite une connexion",
        "Teilen erfordert eine Verbindung",
        "Для общего доступа нужно подключение",
        "المشاركة تتطلب اتصالاً",
        "साझाकरण के लिए कनेक्शन चाहिए",
        "A megosztáshoz kapcsolat szükséges",
        "Sdílení vyžaduje připojení",
        "Udostępnianie wymaga połączenia",
    ),
    "Sharing unavailable (protected note)": T(
        "Compartir no disponible (nota protegida)",
        "Condivisione non disponibile (nota protetta)",
        "Partage indisponible (note protégée)",
        "Teilen nicht verfügbar (geschützte Notiz)",
        "Общий доступ недоступен (защищённая заметка)",
        "المشاركة غير متاحة (ملاحظة محمية)",
        "साझाकरण उपलब्ध नहीं (संरक्षित नोट)",
        "Megosztás nem elérhető (védett jegyzet)",
        "Sdílení není k dispozici (chráněná poznámka)",
        "Udostępnianie niedostępne (chroniona notatka)",
    ),
    "Sharing ✓": T(
        "Compartido ✓",
        "Condiviso ✓",
        "Partagé ✓",
        "Geteilt ✓",
        "Общий доступ ✓",
        "مشترك ✓",
        "साझा ✓",
        "Megosztva ✓",
        "Sdíleno ✓",
        "Udostępniono ✓",
    ),
    "Show note details": T(
        "Mostrar detalles de la nota",
        "Mostra dettagli nota",
        "Afficher les détails de la note",
        "Notizdetails anzeigen",
        "Показать сведения о заметке",
        "إظهار تفاصيل الملاحظة",
        "नोट विवरण दिखाएँ",
        "Jegyzet részleteinek megjelenítése",
        "Zobrazit podrobnosti poznámky",
        "Pokaż szczegóły notatki",
    ),
    "Showing cached data": T(
        "Mostrando datos en caché",
        "Visualizzazione dati in cache",
        "Affichage des données en cache",
        "Zwischengespeicherte Daten werden angezeigt",
        "Показаны кэшированные данные",
        "عرض البيانات المخبأة",
        "कैश डेटा दिखाया जा रहा है",
        "Gyorsítótárazott adatok megjelenítése",
        "Zobrazují se uložená data",
        "Wyświetlane są dane z pamięci podręcznej",
    ),
    "Sign in and connect to your server to save.": T(
        "Inicia sesión y conéctate a tu servidor para guardar.",
        "Accedi e connettiti al server per salvare.",
        "Connectez-vous et reliez-vous à votre serveur pour enregistrer.",
        "Melden Sie sich an und verbinden Sie sich mit Ihrem Server, um zu speichern.",
        "Войдите и подключитесь к серверу, чтобы сохранить.",
        "سجّل الدخول واتصل بالخادم لحفظ التغييرات.",
        "सहेजने के लिए साइन इन करें और अपने सर्वर से कनेक्ट करें।",
        "Jelentkezzen be és csatlakozzon a kiszolgálóhoz a mentéshez.",
        "Chcete-li ukládat, přihlaste se a připojte se k serveru.",
        "Zaloguj się i połącz z serwerem, aby zapisać.",
    ),
    "Sign in to create notes.": T(
        "Inicia sesión para crear notas.",
        "Accedi per creare note.",
        "Connectez-vous pour créer des notes.",
        "Melden Sie sich an, um Notizen zu erstellen.",
        "Войдите, чтобы создавать заметки.",
        "سجّل الدخول لإنشاء ملاحظات.",
        "नोट बनाने के लिए साइन इन करें।",
        "Jegyzetek létrehozásához jelentkezzen be.",
        "Chcete-li vytvářet poznámky, přihlaste se.",
        "Zaloguj się, aby tworzyć notatki.",
    ),
    "Some notes could not be updated (%lld failed).": T(
        "No se pudieron actualizar algunas notas (%lld fallaron).",
        "Impossibile aggiornare alcune note (%lld non riuscite).",
        "Certaines notes n’ont pas pu être mises à jour (%lld échecs).",
        "Einige Notizen konnten nicht aktualisiert werden (%lld fehlgeschlagen).",
        "Не удалось обновить некоторые заметки (сбоев: %lld).",
        "تعذّر تحديث بعض الملاحظات (فشل %lld).",
        "कुछ नोट अपडेट नहीं हो सके (%lld विफल)।",
        "Néhány jegyzet nem frissíthető (%lld sikertelen).",
        "Některé poznámky se nepodařilo aktualizovat (selhalo: %lld).",
        "Niektóre notatki nie mogły zostać zaktualizowane (niepowodzeń: %lld).",
    ),
    "Stop sharing": T(
        "Dejar de compartir",
        "Interrompi condivisione",
        "Arrêter le partage",
        "Freigabe beenden",
        "Отключить общий доступ",
        "إيقاف المشاركة",
        "साझाकरण बंद करें",
        "Megosztás leállítása",
        "Zastavit sdílení",
        "Zatrzymaj udostępnianie",
    ),
    "Stop sharing selected notes?": T(
        "¿Dejar de compartir las notas seleccionadas?",
        "Interrompere la condivisione delle note selezionate?",
        "Arrêter le partage des notes sélectionnées ?",
        "Freigabe der ausgewählten Notizen beenden?",
        "Отключить общий доступ для выбранных заметок?",
        "إيقاف مشاركة الملاحظات المحددة؟",
        "चयनित नोट का साझाकरण बंद करें?",
        "Leállítja a kijelölt jegyzetek megosztását?",
        "Zastavit sdílení vybraných poznámek?",
        "Zatrzymać udostępnianie wybranych notatek?",
    ),
    "Sub-note": T(
        "Subnota",
        "Sottonota",
        "Sous-note",
        "Untergeordnete Notiz",
        "Подзаметка",
        "ملاحظة فرعية",
        "उप-नोट",
        "Alárendelt jegyzet",
        "Podřízená poznámka",
        "Podnotatka",
    ),
    "Syncing…": T(
        "Sincronizando…",
        "Sincronizzazione…",
        "Synchronisation…",
        "Synchronisiere …",
        "Синхронизация…",
        "جارٍ المزامنة…",
        "सिंक हो रहा है…",
        "Szinkronizálás…",
        "Synchronizace…",
        "Synchronizacja…",
    ),
    "The root notebook cannot be moved.": T(
        "El cuaderno raíz no se puede mover.",
        "Il taccuino radice non può essere spostato.",
        "Le carnet racine ne peut pas être déplacé.",
        "Das Stamm-Notizbuch kann nicht verschoben werden.",
        "Корневой блокнот нельзя переместить.",
        "لا يمكن نقل دفتر الملاحظات الجذر.",
        "रूट नोटबुक को नहीं ले जा सकते।",
        "A gyökér jegyzetfüzet nem helyezhető át.",
        "Kořenový poznámkový blok nelze přesunout.",
        "Notatnika głównego nie można przenieść.",
    ),
    "These %lld notes will no longer be publicly accessible.": T(
        "Estas %lld notas dejarán de ser accesibles públicamente.",
        "Queste %lld note non saranno più accessibili pubblicamente.",
        "Ces %lld notes ne seront plus accessibles publiquement.",
        "Diese %lld Notizen sind nicht mehr öffentlich zugänglich.",
        "Эти заметки (%lld) больше не будут общедоступны.",
        "لن تكون هذه الـ %lld ملاحظات متاحة للعامة بعد الآن.",
        "ये %lld नोट अब सार्वजनिक रूप से उपलब्ध नहीं होंगे।",
        "Ezek a(z) %lld jegyzet többé nem lesznek nyilvánosan elérhetők.",
        "Těchto %lld poznámek již nebude veřejně dostupných.",
        "Te %lld notatki nie będą już publicznie dostępne.",
    ),
    "This note cannot be shared.": T(
        "Esta nota no se puede compartir.",
        "Questa nota non può essere condivisa.",
        "Cette note ne peut pas être partagée.",
        "Diese Notiz kann nicht geteilt werden.",
        "Эту заметку нельзя сделать общей.",
        "لا يمكن مشاركة هذه الملاحظة.",
        "यह नोट साझा नहीं किया जा सकता।",
        "Ez a jegyzet nem osztható meg.",
        "Tuto poznámku nelze sdílet.",
        "Tej notatki nie można udostępniać.",
    ),
    "Top level (under Notes)": T(
        "Nivel superior (bajo Notas)",
        "Livello superiore (sotto Note)",
        "Niveau supérieur (sous Notes)",
        "Oberste Ebene (unter Notizen)",
        "Верхний уровень (под «Заметки»)",
        "المستوى الأعلى (تحت الملاحظات)",
        "शीर्ष स्तर (नोट्स के अंतर्गत)",
        "Legfelső szint (a Jegyzetek alatt)",
        "Nejvyšší úroveň (pod Poznámky)",
        "Poziom najwyższy (pod Notatkami)",
    ),
    "Unlock the note to preview matches in the body.": T(
        "Desbloquea la nota para previsualizar coincidencias en el cuerpo.",
        "Sblocca la nota per vedere le corrispondenze nel corpo.",
        "Déverrouillez la note pour prévisualiser les correspondances dans le corps.",
        "Entsperren Sie die Notiz, um Treffer im Inhalt in der Vorschau zu sehen.",
        "Разблокируйте заметку, чтобы просматривать совпадения в тексте.",
        "افتح قفل الملاحظة لمعاينة التطابقات في المحتوى.",
        "मिलान का पूर्वावलोकन करने के लिए नोट अनलॉक करें।",
        "Oldja fel a jegyzet zárolását az egyezések előnézetéhez a szövegben.",
        "Odemkněte poznámku pro náhled shod v těle textu.",
        "Odblokuj notatkę, aby zobaczyć dopasowania w treści.",
    ),
    "Unlock this protected note before moving.": T(
        "Desbloquea esta nota protegida antes de moverla.",
        "Sblocca questa nota protetta prima di spostarla.",
        "Déverrouillez cette note protégée avant de la déplacer.",
        "Entsperren Sie diese geschützte Notiz, bevor Sie sie verschieben.",
        "Разблокируйте эту защищённую заметку перед перемещением.",
        "افتح قفل هذه الملاحظة المحمية قبل النقل.",
        "स्थानांतरण से पहले इस संरक्षित नोट को अनलॉक करें।",
        "A védett jegyzet feloldása kötelező az áthelyezés előtt.",
        "Před přesunem odemkněte tuto chráněnou poznámku.",
        "Odblokuj chronioną notatkę przed przeniesieniem.",
    ),
    # Format-string keys (Swift String Catalog / String(localized:) interpolation)
    "Last changed %@": T(
        "Última modificación: %@",
        "Ultima modifica: %@",
        "Dernière modification : %@",
        "Zuletzt geändert: %@",
        "Последнее изменение: %@",
        "آخر تغيير: %@",
        "अंतिम बदलाव: %@",
        "Utolsó módosítás: %@",
        "Naposledy změněno: %@",
        "Ostatnia zmiana: %@",
    ),
    "Move “%@” under “%@”? The note will appear in the new location in the tree.": T(
        "¿Mover «%@» bajo «%@»? La nota aparecerá en la nueva ubicación en el árbol.",
        "Spostare «%@» sotto «%@»? La nota apparirà nella nuova posizione nell’albero.",
        "Déplacer « %@ » sous « %@ » ? La note apparaîtra au nouvel emplacement dans l’arborescence.",
        "„%@“ unter „%@“ verschieben? Die Notiz erscheint im Baum am neuen Ort.",
        "Переместить «%@» под «%@»? Заметка появится в дереве в новом месте.",
        "نقل «%@» تحت «%@»؟ ستظهر الملاحظة في الموقع الجديد في الشجرة.",
        "«%@» को «%@» के अंतर्गत ले जाएँ? नोट ट्री में नए स्थान पर दिखेगा।",
        "«%@» áthelyezése «%@» alá? A jegyzet az új helyen jelenik meg a fában.",
        "Přesunout „%@“ pod „%@“? Poznámka se ve stromu zobrazí na novém místě.",
        "Przenieść „%@” pod „%@”? Notatka pojawi się w drzewie w nowym miejscu.",
    ),
}

_ui_path = Path(__file__).resolve().parent / "ui_strings_extra.py"
_ui_spec = importlib.util.spec_from_file_location("ui_strings_extra", _ui_path)
_ui_mod = importlib.util.module_from_spec(_ui_spec)
assert _ui_spec.loader is not None
_ui_spec.loader.exec_module(_ui_mod)
STRINGS.update(_ui_mod.UI_EXTRA)


def build_xcstrings() -> dict:
    out: dict = {
        "sourceLanguage": "en",
        "strings": {},
        "version": "1.0",
    }
    strings = out["strings"]
    for key, locs in STRINGS.items():
        entry: dict = {
            "localizations": {
                "en": {"stringUnit": {"state": "translated", "value": key}},
            }
        }
        for loc in LOCALES:
            entry["localizations"][loc] = {
                "stringUnit": {"state": "translated", "value": locs[loc]}
            }
        strings[key] = entry
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out_path = root / "Trinote" / "Resources" / "Localizable.xcstrings"
    data = build_xcstrings()
    out_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(STRINGS)} keys)")


if __name__ == "__main__":
    main()
