#!/usr/bin/env swift
// Generates BoxiconsCatalog.generated.swift from vendored boxicons.css (v2.1.4).
// Run from repo root: swift Scripts/generate_boxicons_catalog.swift

import Foundation

let boxiconsVersion = "2.1.4"
let repoRoot = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let cssURL = repoRoot
    .appendingPathComponent("Trinote/Resources/BoxiconsVendor/boxicons.css")
let outputURL = repoRoot
    .appendingPathComponent("Trinote/Core/Utilities/BoxiconsCatalog.generated.swift")

guard let css = try? String(contentsOf: cssURL, encoding: .utf8) else {
    fputs("error: could not read \(cssURL.path)\n", stderr)
    exit(1)
}

// Matches: .bx-calendar:before { content: "\ea15"; }
let pattern = #"\.([\w-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)";\s*\}"#
guard let regex = try? NSRegularExpression(pattern: pattern) else {
    fputs("error: invalid regex\n", stderr)
    exit(1)
}

var codepoints: [String: UInt32] = [:]
let nsRange = NSRange(css.startIndex..<css.endIndex, in: css)
for match in regex.matches(in: css, range: nsRange) {
    guard
        let classRange = Range(match.range(at: 1), in: css),
        let hexRange = Range(match.range(at: 2), in: css),
        let value = UInt32(css[hexRange], radix: 16)
    else { continue }
    codepoints[String(css[classRange])] = value
}

let sortedKeys = codepoints.keys.sorted()
var lines: [String] = []
lines.append("// Generated by Scripts/generate_boxicons_catalog.swift — do not edit.")
lines.append("// Boxicons v\(boxiconsVersion)")
lines.append("")
lines.append("import Foundation")
lines.append("")
lines.append("enum BoxiconsCatalog {")
lines.append("    static let version = \"\(boxiconsVersion)\"")
lines.append("    static let fontPostScriptName = \"boxicons\"")
lines.append("")
lines.append("    static let codepoints: [String: UInt32] = [")
for key in sortedKeys {
    guard let cp = codepoints[key] else { continue }
    lines.append("        \"\(key)\": 0x\(String(cp, radix: 16)),")
}
lines.append("    ]")
lines.append("")
lines.append("    /// All icon class keys (bx-, bxs-, bxl-) for the picker grid.")
lines.append("    static let allIconClasses: [String] = [")
for key in sortedKeys {
    lines.append("        \"\(key)\",")
}
lines.append("    ]")
lines.append("}")

let output = lines.joined(separator: "\n") + "\n"
try output.write(to: outputURL, atomically: true, encoding: .utf8)
print("Wrote \(sortedKeys.count) icons to \(outputURL.path)")
